version: '3.2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: noud
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: parki
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 1000:8080

  app:
    build: .
    links:
      - postgres
    ports:
      - 9094:9094
