version: '3.2'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parki
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
